---
version: "3.5"
services:
    ssg:
        build:
            context: ./ssg-build
        volumes:
            - "./src:/srv/jekyll:rw"
        command: ["jekyll", "build", "--future"]

    web:
        image: nginx:alpine
        volumes:
            - "./src/_site:/usr/share/nginx/html:ro"
            - "./web/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro"
        depends_on:
            - ssg
        labels:
            - com.centurylinklabs.watchtower.enable=true
        restart: always

    tor:
        image: goldy/tor-hidden-service
        environment:
            WEB_TOR_SERVICE_HOSTS: "80:web:80"
            WEB_TOR_SERVICE_VERSION: 3
            WEB_TOR_SERVICE_KEY: "${WEB_TOR_SERVICE_KEY}"
        labels:
            - com.centurylinklabs.watchtower.enable=true
        restart: always

    # Watchtower ensures that the `watchtower.enable`'d containers are
    # automatically restarted from newly pulled (updated) base images.
    watchtower:
        image: containrrr/watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        restart: on-failure
        # Schedule updates for 1:30 AM on 15th day of every 2nd month.
        command: --schedule "0 30 1 15 */2 *" --cleanup --label-enable
